# Generated by Django 3.2.5 on 2021-09-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorptec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categories_name', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
