# Generated by Django 3.2.5 on 2021-09-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorptec', '0003_auto_20210911_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(blank=True, upload_to='product_pics')),
                ('product_description', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
