# Generated by Django 3.2.5 on 2021-09-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorptec', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='scorptec.Category'),
        ),
    ]
