# Generated by Django 3.2.5 on 2021-09-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorptec', '0009_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
